### ISSUE TITLE
[question] developpent status

### ISSUE THREAD

**Issue by GMagician** [MrAlvin/RAMPS-1.4.4#3]
Hi MrAlvin,

sorry to ask, how about board development? is it still active?
I think I'll buy a board of yours and change connectors to molex kk254 series (or Chinese KF2510) (where/if possible). I stopped my development due to high price (more than €50 excluded pcb and some components) and inability to find-out good solutions.

**Comment by jalanjarosz** [comment]
MrAlvin is continuing his development. 

I have a Rev C1 Board that I’m testing on a MEGA and eventually an Adafruit Grand Central M4.  

Mr Alvin has another board revision that is being finished up so I can test as well.

**Comment by GMagician** [comment]
@jalanjarosz glad to hear that, let me know about AGCM4, I have that kind of board and I integrated it into Marlin but I never had possibility to test code due to lack of valid shields.
I was trying to develop my own shield because I didn't like connectors used on ramps (1.4 and also this). I replaced them, in my 1.4, with KF2510 and I'm going to do the same with 1.4.4, if there is enough space to solder them

**Comment by jalanjarosz** [comment]
I modified a RAMPS 1.6 to get my AGCM4 working first.  This is a much better solution.  

How is Marlin 2 support for the ATSAMD chip going?

**Comment by GMagician** [comment]
> How is Marlin 2 support for the ATSAMD chip going?

I tested onboard SD, analog inputs and serial communication (via USB). Latter needs a fix (already merged in Adafruit repository) but not yet released in latest framework release.
Digital inputs and LCD should work.
Neopixels should work (I've done some test with the one on the board using Marlin)
SmartEEPROM is working (if shield doesn't have eeprom)
TMC spi should also work
I uploaded Marlin and it seems to work (using repetier) but without a shield is almost impossible to do accurate tests

**Comment by GMagician** [comment]
> I modified a RAMPS 1.6 to get my AGCM4 working first

I don't like 1.6 connectors (these are commons to all ramps) and I would like to use TMC via spi (1.6 needs wires because it doesn't have jumpers)

**Comment by GMagician** [comment]
I would like to integrate also eeprom chip (external one mounted on AGCM4) instead of SmartEEPROM but I stopped all development waiting for a valid shield

**Comment by GMagician** [comment]
USB fix references:
https://github.com/adafruit/ArduinoCore-samd/pull/164

**Comment by GMagician** [comment]
@jalanjarosz what level of test have you done with AGCM4?

**Comment by jalanjarosz** [comment]
I have a complete setup in Klipper FW, which has support for the ATSAMD chip.

I first modified a BTT RAMPS v1.6 to work with 3v3 logic and installed DRV8825 step sticks.   I have a RRD display and the Fystec MKS Mini with Neopixel's displays working (individually), endstops, thermistors, steppers, and fans.  I've tested the MOSFETS on the RAMPS boards, but since they are not rated for 3v3 logic, I would not run them without external MOSFETS.

The RRD display needs a 5v step up converter in order to increase the voltage for the back light. The  MKS Mini display works without any hardware modifications.

I was going to modify a BTT RAMPS 1.6+ board next and configure TMC2130's, but @MrAlvin supplied me with one of his v1.4.4 boards, which I'm working that up now.

I've attached the document I wrote regarding the RAMPS v1.6 journey.  Hopefully it may provide some help.

I'm going to use one v1.4.4 board on a RE-ARM with Marlin on my A8 and two 1.4.4 board with AGCM4's on my CoreXY.

[RAMPS Modifications for AGCM4.pdf](https://github.com/MrAlvin/RAMPS-1.4.4/files/3894773/RAMPS.Modifications.for.AGCM4.pdf)

**Comment by GMagician** [comment]
Wow, really detailed document, my compliments.
Just one note, as stated in Adafruit web site, AGCM4 max input voltage is 9V not 12V then using ramps with 12VDC is not a good choice, this is what they told me:

> The 5V voltage regulator can survive 12V, but we suggest staying in the 7V-to-9V range

https://forums.adafruit.com/viewtopic.php?f=63&t=151881&p=749978&hilit=12V#p749978

**Comment by MrAlvin** [comment]
> Hi MrAlvin,
> 
> sorry to ask, 

I love questions, so please do ask :-) 

> how about board development? is it still active?

Yes it is still active. 
It is however going somewhat slow, as these past several years I have (again and again) had some surprising heath challenges. 
So far I have fortunately found solutions each time, but each time something new happens, it slows me down, for a period anyway. 

> I think I'll buy a board of yours and change connectors to molex kk254 series (or Chinese KF2510) (where/if possible). 

I will be happy to ship you a board.  I could send you one of the latest pre-release versions (newest version is Rev.C4. 
And I will be ordering a Rev.C5 very soon now. 

Since Rev.C1 all the basic functionality has been working fine. Like: endstops, steppers, TMC2130 via SPI, all mosfets, PS-on control, inductive Z-min  port, and more. 
So right now I am mainly making small adjustments. 

One of the latest adjustments has been an option for two more DC-DC MP1584 modules. So there can, for instance, be a proper 8V supply for Vin, and a  more powerful 5V rail. 

And likewise, I (just yesterday) made sure that it is possible to fit the KF2510 style connectors directly on the shield (for all stepper drivers). 

I am assembling an Ultimaker (Original) clone, and the electronics fit in the "basement", but is mounted upside down! So all connectors will be pulled on (as in being pulled out!) by gravity, under regular and normal operations. 
So when I looked at this, I simply HAD TO make sure that it is possible to use 'locking-style connectors' for everything. 
For the steppers it will be possible to fit the KF2510 style connectors directly on the shield, but for everything else, some daughter-boards will be needed, so now I just need to make sure that the daughter-boards can be held in place by a screw option. 

About names for the KF2510 style connectors. 
I use some connectors called NSG, as I bought many of those some years ago. But it seems to me that the different brands are so close to being the same, that they can safely be mixed-and-matched. 

Because JLCPCB has made a small change in their prototype offers, I am needing to adjust my strategy about how I order a batch of prototype boards. 
They used to only have a limit of max 10x10 cm in the layout, even if I would be able to fit several designs into the 10x10 cm.  So I used to have three different layouts of 10x10cm boards made each time I would order a PCB shipment.  As I am also testing LCD adapters (and more) each time I do a new revision of the 1.4.4 shield. 

But now I will most likely need to  make many designs for each order. 
I currently have two different external mosfet designs in the pipeline. And three different LCD adapters. And the daughter boards with KF2510 connectors. 

I also have a design for a 'motherboard' (sort of like an Arduino Mega), but so it is easy to use the RAMPS shield for testing with the STM32 or ESP32 family of processors. 

As I intend to use this Ultimake Clone 3D printer, as a test platform for ideas, I have also prepared some PCB designs so it will be easy to try out some new stuff.  The space is however limited, so I find myself needing to do some specialized PCB layouts, in order to optimize the use of the limited space in the "basement" of the Ultimake Clone. 

Also, James has helped me become curious about using Klipper.  And I see some 'hats' needing to be designed for some Klipper testing. 

So all in all, I have eight different PCB designs ready to be produced next time I order some PCBs. 

>I stopped my development due to high price (more than €50 excluded pcb and some components) and inability to find-out good solutions.

Ah yes, development can indeed be a bit expensive. 

But like I said, I will be happy to send you a pre-release board (for free), so you can have something to do some testing with.  So long as I have PCBs left over from testing the revisions, they might as well be put to good use.  My only request is, that you will consider making a small donation towards the cost of postage for the board to be shipped to your location. 
Okay? 

You are also welcome to wait, until a Release Candidate is ready.  It is your choice. Okay?

**Comment by GMagician** [comment]
> It is however going somewhat slow, as these past several years I have (again and again) had some surprising heath challenges.
So far I have fortunately found solutions each time, but each time something new happens, it slows me down, for a period anyway.

That's not a good news but I hope you feel better now, health is most important thing and has no price

About your board status, important for AGCM4 is a lower power rail (max 9V). KF2510 is just a model that is better then the ones used by ramps boards. Every "lockable" connector is a good choice. I was looking to Molex kk254 because of more current they support (till 3A if I remember correctly), even better than kf2510 (1A) and are exchangeable.

It will be better to have all connectors (thermistors, pwm fans) lockable, this is to be sure everything rest in correct position. Good idea a daughter board since you have no free area (I think) to properly space connectors.

> My only request is, that you will consider making a small donation towards the cost of postage for the board to be shipped to your location.

That should not be a option and not only pay for postage. I think it's "more respectful" to pay something more then that

> So all in all, I have eight different PCB designs ready to be produced next time I order some PCBs

wow, sure this is just an hobby and not your job? :-D

> Ah yes, development can indeed be a bit expensive

In this case I stopped before, even if I may afford such price for my printer, it will be useless for most people (my idea was similar to yours, develop this and post all source to the community)

> You are also welcome to wait, until a Release Candidate is ready. It is your choice. Okay?

What I would like to have is a board where I can:
1) Use my AGCM4 board (powered at max 9V)
2) Use TMC with SPI (I don't have them because I'm waiting for a valid tmc5161 stepstick)
    Do board has vin/vmot protector diode?
3) Use my 12864 LCD
4) Use 24V for bed (190W) and hotend (50W)
5) Use 12V/5V on fans (hard to find 24V fans)
6) Use my 5V bltouch (but in future I may use a pinda2 sensor)
7) Use "lockable" connectors (kf2510, kk254, nsg)

I don't know how far is current development from that and not sure if it will ever satisfy these points.

Sorry I'm so demanding but I made so many changes to my old ramps 1.4 that now it looks more like battlefield than a board.

Please, I may consider your offer, can you tell me how many points I can satisfy with current revision?

Many many thanks for your patience

**Comment by jalanjarosz** [comment]
I'll try to answer some of the design questions based on schematics.  I have a rev C1 board that I'm working with now

> 1.  Use my AGCM4 board (powered at max 9V)

Rev C1 - Has a DC-DC step-down module to regulate 12v as an option.  Vin can be supplied with 12v by bridging junction J20 or when cutting trace, voltage will be stepped down via diode D9 and D10.  Basically burning off excess voltage as heat

Rev C5 has 4 options:
1) 12v via DC-DC module on underside of shield
2) Lower option 1 via diode D12
3) Lower option 2 via diode D14, D15, D16
4) 8.5v via secondary DC-DC module

> 2. >     Use TMC with SPI (I don't have them because I'm waiting for a valid tmc5161 stepstick)

TMC traces are built in like BTT RAMPS v1.6+ boards

> 3. >     Do board has vin/vmot protector diode?

No - Technically only needed for 3v3 logic per: https://learn.watterott.com/silentstepstick/faq/#what-is-the-difference-between-silentstepsticks-with-3-5v-and-5v-logic-voltage

I have ordered some in at $0.85 USD: https://www.aliexpress.com/item/32917618800.html?spm=2114.12010615.8148356.2.2bc3274bNQ2p3V

It's up to @MrAlvin to see if there is enough board space left as I know he's tried, up until Rev C4/C5 to maintain the RAMPS footprint

> 4. >     Use my 12864 LCD

Not a problem with @MrAlvin LCD board.  The MKS Mini 12864 works with 3v3 volt or 5v, the RRD 12864 needs 5v

> 5. >     Use 24V for bed (190W) and hotend (50W)

@MrAlvin designed the RAMPS v1.4.4 to drive a "typical" hot-end and heated-bed with the headed-bed to be between 8-12A draw with electronics only getting warm.  He has a temp goal of about 60C.  External MOSFETS should be considered for higher draw components with total board draw not to exceed the 20A connector limit of the power input.

Heated-Bed uses dual IRLB8743 MOSFETS and the hot-end has a single.  There are 3 fan pins, each with their own A03400 MOSFET

> 6. >     Use 12V/5V on fans (hard to find 24V fans)

Rev C1 allows for 24v or 12v fan selectable via jumper J2
Rev C4/C5 allows for 24v or 12v fan selectable via jumper J2 or 5v with additional DC-DC module

> 7. >     Use my 5V bltouch (but in future I may use a pinda2 sensor)

BLTouch should not be an issue  My v2.1 and newer supports 5v or 3v3 logic with 5v needed for pin retraction.  Servo's can be 5v via bridging J39, or you can use a 5v step-up converter if necessary.
Rev C1 and C4/C5 have an option for a 12v z-sensor like a NPN via J8

> 8. >     Use "lockable" connectors (kf2510, kk254, nsg)

Rev C1 board has all endstop, servo, and stepper connectors as standard 2.54mm Dupont headers.  

Regarding voltages go, the RAMPS line has two voltage rails: 12v (unless you modify to 24v) and 5v/Vcc, which is where my RAMPS mods had to be made.  @MrAlvin RAMPS v1.4.4 has three voltage rails: 24v/12v (high voltage), Vcc/Logic (5v or 3v3) and 5v.  Board C4/C5 add the option for 8.5v to just power Vin for the MCU so excess voltage is tuned down versus "burned up".

My C1 board has a built-on 24LS256 EEPROM connected thought the I2C header, which it looks like Marlin supports.

Overall, I think @MrAlvin v1.4.4 RAMPS design fulfills what you are looking for.

**Comment by jalanjarosz** [comment]
I just double checked my emails with @MrAlvin and the C4 schematic regarding this:

> Do board has vin/vmot protector diode?

Rev C4 board has two additional diodes: D17/D18 with the following note:
**D17 and D18 protects the  Watterott TMCxxx SilentStepstick internal 3-5V generation, when the shield is USB powered only.**

**Comment by GMagician** [comment]
@jalanjarosz thanks for your feedback, really detailed.
Just some questions:

>  No - Technically only needed for 3v3 logic per: https://learn.watterott.com/silentstepstick/faq/#what-is-the-difference-between-silentstepsticks-with-3-5v-and-5v-logic-voltage

but what is vio applied to stepsticks? AFAIK new stepstick are 3.3-5V or am I wrong?
However Rev C4 as per your last comment seems to solve issues

> Board C4/C5 add the option for 8.5v to just power Vin

then if I feed my board with 24V I need for sure 1 step down to 8.5V and one 5 or 12V for fans? Right?

my LCD is powered with 5V now (mega2560) don't know if it can work with 3.3V.

Only missing thing, on C4/C5 is "lockable" connectors. But as stated by @MrAlvin they will be also added for its needs of "reverse" board mounting. I think I have to wait for C6 release for all of this, but currently is really a fullopt board!

**Comment by GMagician** [comment]
I may also think to get a C4/C5 now and finalize AGCM4 Marlin support, then buy a C6 to be used by my printer.
Where to source componets? Digikey/mouser? what is the price for all of them (more or less)?

**Comment by MrAlvin** [comment]
Yes, health is very essential. But I try to remain patient, and focused ofn finding solutions. Right now I am waiting for the second round of experts about sleep apne. 


> About your board status, important for AGCM4 is a lower power rail (max 9V). 

There are now several ways, implemented on the shield, so this can be achieved. I will share with you, the current schematics, and show how this can be achieved.  The ideal way is to simply use a dedicated DC-DC switchg mode modue, and set the output to what ever voltage you find to be optimal. 
 

> KF2510 is just a model that is better then the ones used by ramps boards. Every "lockable" connector is a good choice. 

I fully agree. 

> I was looking to Molex kk254 because of more current they support (till 3A if I remember correctly), even better than kf2510 (1A) and are exchangeable.

Ah, good to know.  I had not yet compared amp limits for ther different connectors.


> It will be better to have all connectors (thermistors, pwm fans) lockable, this is to be sure everything rest in correct position. Good idea a daughter board since you have no free area (I think) to properly space connectors.

Indeed, it is better, but it really is a space issue, and so far I have only been able to solve it by using daughter boards. 


> > My only request is, that you will consider making a small donation towards the cost of postage for the board to be shipped to your location.
> 
> That should not be a option and not only pay for postage. I think it's "more respectful" to pay something more then that

Okay. I appreciate your attitude :-)  We can definetely find a solution, and balance, so we will both be happy. 


> > So all in all, I have eight different PCB designs ready to be produced next time I order some PCBs
> 
> wow, sure this is just an hobby and not your job? :-D

lol :-) 
What can I say, I enjoy my hobby :-) 


> What I would like to have is a board where I can:
> 
> 1. Use my AGCM4 board (powered at max 9V)

This is now available, in more ways than one. But I consider the optimal way to be dedicate one of the three DC-DC switch mode modules to this task. 

As you might recall, the original design framework  was "same size shield". 
But for revision C4, I decided to go a little beyond, and to test out two options of how to specifically address this issue of getting a lower voltage to the processor board. 
These two new options makes the board bigger, but it is implemented in such a way that the extra section can simply be cut off and we are back to the original size again. 

I will show you in the schematics, and within a few days I am also likely to have pictures. Okay? 

> 2. Use TMC with SPI (I don't have them because I'm waiting for a valid tmc5161 stepstick)

To use SPI for a stepper driver, is individually jumper selectable for each stepper driver. 


>    Do board has vin/vmot protector diode?

Yes. But perhaps we do not think of the same answer. 


Similar to D1 on the original RAMPS board, the 1.4.4 shield also has a dedicated diode, right before the Arduino Vin pin. So it is NOT possible to send reverse voltage to the Arduino. 


There is also a 5 Amp  diode that protects the Vmot rail.  So it is also NOT possible to send reverse voltage to thre stepper drivers. 

But this imposes a limit of max 5 amp for all stepper drivers, and not everyone will be happy with this 5 amp limit for all stepper drivers. So it is possible to by-pass this Vmot diode. 

hmmm... I will need to see if I could prepare, so it would be easy to do a mod/hack, to add some wires and diodes, so it would be simple to have 2x or 3x 5 amp diodes for the Vmot rails. 


Or are you thinking about the 'stepstick loging voltaege protection diode? 

Wattrott mentiones another "protection diode" for their TMCxxxx stepsticks. As the Watterott TMC stepsticks are set up to take power fr the internal logic of the stepper driver chip, from the Vmot rail. 
As of revision C4, a diode has been added from Vcc to Vmot, as well as a diode from the Always-5V rail to Vmot rail. 
This is to help ensure that the TMC internal voltage regulators (for the logic power supply), always have something to work with. 


> 3. Use my 12864 LCD

I have several LCD adapter boards, as Due and Re-ARM each have their LCD issues.  

But in general any 3V and 5V issues for LCD have been solved, by sending 5V to a pin on Aux-3, that is not being used for anything on the Original RAMPS shield. 

As luck would have it, then all signals returning from the RRD LCD design(which is what most 12864 LCDs are), is always only 3V. So it is possible (and safe) to send 5V to the LCD (so contrast etc. is good), and SD card signals will still always only be 3V.  



> 4. Use 24V for bed (190W) and hotend (50W)

The 1.4.4 shield was specifically designed to be operated at 24V.  
So far I have successfully tested up to 12A for the bed.  I have only done very limited testing on the mosfet for the hotend. But I seem to recall that 5-6 amp is no problem at all.  So 50W is definately no probem. 



> 5. Use 12V/5V on fans (hard to find 24V fans)

Until revision C4 it was possible to select 24V or 12V for the fan mosfets. With revision C5 it is now possible to have 5V sent to two of the three fan mosfets, by changbing some jumpers. 


> 6. Use my 5V bltouch (but in future I may use a pinda2 sensor)

As revision C4 introduced a dedcated DC-DC switch mode module for an additional max 3 amp, 5V power rail, thereshould be plenty of power to drive a bltouch. And thus it is no longer necessary to draw 5V from the processor board. 



> 7. Use "lockable" connectors (kf2510, kk254, nsg)

I think we covered this one. With revision C5 it is now possible to use 'lockable' connectors for the stepper drivers, directly on the shield, but it will still be necessary to use daughter boards for the rest of the connectors.


> I don't know how far is current development from that and not sure if it will ever satisfy these points.
> 
> Sorry I'm so demanding but I made so many changes to my old ramps 1.4 that now it looks more like battlefield than a board.

Well, it seems to me, that since yesterday, it is now possible to fulfill all of these requsts. 
So I do not think that they are very demanding - as I have obviously had the same wishes myself :-) 


> Please, I may consider your offer, can you tell me how many points I can satisfy with current revision?


The newest boards I have is C4, and it is not fully possible to mount 'lockable' connectors for all stepper drivers. 
So only revision C5 will fully address all of the points. 



> Many many thanks for your patience

You are very welcome. And thank you for your interest in this project.

**Comment by jalanjarosz** [comment]
> but what is vio applied to stepsticks? AFAIK new stepstick are 3.3-5V or am I wrong?
> However Rev C4 as per your last comment seems to solve issues

MCU Vcc is applied to the step stick's.   So AGCM4 would be 3v3.  Yes the Schottkey diodes are recommended/needed when powering a 3v3 MCU over USB.   I typically use the "Scotch Tape" hack on the USB-A plug and power the MCU via the barrel jack. 

Vcc is supplied via the MCU's IO pin by default, not the 3v3 or 5v pins. 

> then if I feed my board with 24V I need for sure 1 step down to 8.5V and one 5 or 12V for fans? Right?

You would need three MP1584 DC-DC Step-Down/Buck Converters

> my LCD is powered with 5V now (mega2560) don't know if it can work with 3.3V.

On the v1.4.4 shield, 5v is pulled from the 5v rail of the MCU to power one of the AUX3 pins, which powers the display.  You are fine with the RRD display.

When I did my RAMPS 1.6 mod, I had to use a 5v step-up converter to power the RRD.

**Comment by MrAlvin** [comment]
> I'll try to answer some of the design questions based on schematics. I have a rev C1 board that I'm working with now
......

wow, I am impressed! 

I even consider your answers to better than my own attempt. 
Just brilliant :-) 

So, Thank you.

**Comment by MrAlvin** [comment]
> I may also think to get a C4/C5 now and finalize AGCM4 Marlin support, 

Sounds to me like a good idea.  As it gives a method to get some work done, on actual hardware. 


> then buy a C6 to be used by my printer.

Again, good thinking. And what development is all about :-) 

> Where to source componets? Digikey/mouser? what is the price for all of them (more or less)?

I have all components in stock.  And then some. 
All components are however 'China sourced'. 

All components (at china prices) are less than US$8.  And these days US$ 1 is about the same as  €1. 


Because of fast shipping, and very low count of prototypes per revision,  the PCB becomes a bit expensive.  So my current actual cost per PCB only is about  €7. 


But shipping - from my address in Denmark  -  actually becomes the most expensive part. 
It is possible to send as a non-traceable letter, this is about €4. 
And a traceable letter, is about  €15
A traceable  package is a minimum of €35. 

So, under the right circumstances, it is not all that expensive to make a RAMPS 1.4.4 shield.  And thus I have no problem sharing one pre-release shields for free (or at what ever donation level we can work out). 

As it all becomes about selecting the right style of shipping.

**Comment by GMagician** [comment]
@MrAlvin protection diode I mentioned was to protect tmc internal voltage regulator...adding others 4 diodes for each stepstick is too much and I agree with you about current limits may be bad thing (tmc5161 gives up to 3A....by memory).

> I will show you in the schematics, and within a few days I am also likely to have pictures. Okay?

that's ok, take your time.
I may think to "order" a C4 + LCD and a C5 + dauther then


@jalanjarosz about above diodes, I don't know how board is made but since vio (3.3v) and vmnot (12v/24v) have different routes. You may miss one and not the other, this will burn tmc. Not enough to protect from "only usb" feed.

Thanks guys, very "detailed" answers from both of you.

Going back to my personal cnf, I think I'll need at least 3 dc-dc converter  24->8.5 (MCU), 24->5 (lcd) and 24->12(fans), right?
Where do you source all components?

are the dc-dc you mention these?
https://www.aliexpress.com/item/32341006065.html?spm=a2g0o.detail.1000014.25.4ae42a62GhJoR4&gps-id=pcDetailBottomMoreOtherSeller&scm=1007.13338.128125.0&scm_id=1007.13338.128125.0&scm-url=1007.13338.128125.0&pvid=07b9b16f-a4a9-4259-a46e-1045b5274bd7

**Comment by MrAlvin** [comment]
> @MrAlvin protection diode I mentioned was to protect tmc internal voltage regulator

Ah okay. 
And yes, I did manage to a fond a space (or rather make a space) for such protection diodes. 


> ...adding others 4 diodes for each stepstick is too much 

If the board had space, then I would add them, as they have a good funtionality. But this is a RAMPS board after all. And a RAMPS design, sort of must, be a little primitive - and hackable :-) 

> and I agree with you about current limits may be bad thing (tmc5161 gives up to 3A....by memory).

Design is often about choices. So to protect against reverse voltage is good. But at the cost of limiting funcutionality? Well, what I have tried to do, is make a choice, and then add solder jumpers, so it would be easy for a user, to do a modification - to suit their preference of choice, in the design. 

And many of the adjustmants I have made since revision C1, is much about options, and what if.... I would like to do this?  How can I prepare an option in the layout, so a change is decision can be easy for a user to implement.

And this is one of the reasons I like questions, and 'demands'/'wish lists'.  As this makes it easier  (and interesting for me) to try to prepare solder jumpers etc, so it can become fast and easy for a user to do a hack/modification. 


> > I will show you in the schematics, and within a few days I am also likely to have pictures. Okay?
> 
> that's ok, take your time.

Thank you :-) 


> I may think to "order" a C4 + LCD and a C5 + dauther then

Super. I will do something to collect things for a C4 and LCD. 


And then we will deal with C5 when it will get produced. 



> Going back to my personal cnf, I think I'll need at least 3 dc-dc converter 24->8.5 (MCU), 24->5 (lcd) and 24->12(fans), right?

Yes, that sounds about right. 

Though the LCD does not use very much power, so when the processors Vin voltage is low (7.5V - 8.5V) then the regulator on the processor board can easily power the LCD as well. 
The problem can arise when the Vin is 12V, then the 5V regulator on the porcessor board (the Arduino) will tend to overheat, even when it just needs to supply 100-200mA at 5V. 



> Where do you source all components?

Years ago, I would use rs components, digikey and Rapid. These past few years I have however mainly used ebay. But lately aliexpress has also become a good place to search for components. 


Just recently I have heard about lcsc.com, and this might very well become the digikey killer. And will likely have much more predictable quality than ebay. 

This past year, then ebay has become a bit of a gamble unless you only use the big sellers, like G&C and 'alice109' (or something like that). 



> are the dc-dc you mention these?
> https://www.aliexpress.com/item/32341006065.html


Yes they are the DC-DC modules.

**Comment by GMagician** [comment]
@MrAlvin 

> All components (at china prices) are less than US$8. And these days US$ 1 is about the same as €1.
>
>Because of fast shipping, and very low count of prototypes per revision, the PCB becomes a bit >expensive. So my current actual cost per PCB only is about €7.
>
>But shipping - from my address in Denmark - actually becomes the most expensive part.
>It is possible to send as a non-traceable letter, this is about €4.
>And a traceable letter, is about €15
>A traceable package is a minimum of €35.

I think that package is too much expensive, traceable letter is affordable but it's the price of components + pcb.
Resuming costs:
   Components   €8
   Ramps PCB     €7
   LCD PCB         €7
   Letter              €4
Total alive costs = €26

Right?

**Comment by GMagician** [comment]
Please, can you also share LCD schematic? I would like to double check if this is compatible with AGCM4. That board is not fully mega/due compatible, even oh H/W side
(For sure DAC, MOSI/MISO and something else)

**Comment by MrAlvin** [comment]
> Total alive costs = €26
> 
> Right?

Sounds about right, from the information given. 
It does however seem a bit high (compared to some 1.7 shields that I sold - when working of the 1.7 shield)
So please let me look at the numbers again, to check if my spreadsheets (and component counts) are still as up-to-date as they ought to be. As it has been some time since I last looked at them,

**Comment by MrAlvin** [comment]
> Please, can you also share LCD schematic? I would like to double check if this is compatible with AGCM4. That board is not fully mega/due compatible, even oh H/W side
> (For sure DAC, MOSI/MISO and something else)

Sure I will share. 
Only, I do not yet have a complete schematic.  As I tend to first design the pcb, and just keep the schematic (and the ideas)  in my head. 

This method has the advantage of more freedom to think up layouts, and consider possibilities in a 3D space.

A disadvantage is definitely the slowness to then actually get a schematic to share :-(

**Comment by GMagician** [comment]
> Only, I do not yet have a complete schematic. As I tend to first design the pcb, and just keep the schematic (and the ideas) in my head.

That may be dangerous, one of the schematic advantages is that you may not fail drawing routes in PCB because you have a netlist that helps you

> It does however seem a bit high (compared to some 1.7 shields that I sold - when working of the 1.7 shield)

1.7 ... mmm ... what is main difference between 1.4.4 and 1.7? I though you delayed 1.7 development

**Comment by GMagician** [comment]
@MrAlvin just as reference:
Molex kk: 4A -> https://www.molex.com/webdocs/datasheets/pdf/en-us/0022272041_PCB_HEADERS.pdf
KF2510: 3A -> https://sparks.gogo.co.nz/crimping/index.html (read kf section)

My memory is not working as I would..sigh
